# PlayerTime ${project.version}

# Supports YML or MySQL
database:
  type: YML
# Uncomment when using MySQL
#  host: "localhost"
#  port: 3306
#  username: "root"
#  password: "password"
#  database: "playertime"
#  pool-size: 10

format: "&a{name} has been playing for {days} days, {hours} hours, {minutes} minutes, {seconds} seconds"

messages:
  incorrect-usage: "Too many arguments. Use /ptcheck or /ptcheck <name>"
  never-played-before: "Data for this player was not found. Never played?"
  no-playtime-data: "There was no saved playtime data for this player"