# PlayerTime ${project.version}

# Do not change this
config-version: 1

plugin-prefix: "[&dPlayer&eTime&f]"

# Supports YML or MySQL
database:
  type: YML
# Uncomment when using MySQL
#  host: "localhost"
#  port: 3306
#  username: "root"
#  password: "password"
#  database: "playertime"
#  pool-size: 10

format: "&a{name} has been playing for {days} days, {hours} hours, {minutes} minutes, {seconds} seconds"

gui:
  title: "Top Ten PlayerTimes"
  time-format: "{days} days, {hours} hours, {minutes} minutes, {seconds} seconds"
  item:
    name: "{player}'s time"
    material: "PAPER"
    lore:
    - "Ranked #{slot}"
    - "Time Played: {format}"


messages:
  incorrect-usage: "Too many arguments. Use /ptcheck or /ptcheck <name>"
  never-played-before: "Data for this player was not found. Never played?"
  no-playtime-data: "There was no saved playtime data for this player"