# Bungee Configuration for ${project.name}
#
# Version: ${project.version}

plugin-prefix: "&aPlayTime &8| "
debug-enabled: true

# Import and combine times from remote servers?
import-connected-servers: true

storage:

  # mysql/json
  # json is kinda.. not implemented yet.
  type: mysql

  # Settings for json.
  json:
    file-name: 'times.json'

  # General mysql settings.
  mysql:
    host: 'localhost'
    port: 3306
    username: 'root'
    password: 'password'
    database: 'playtime'

    # Table to use for local times.
    table: 'play-time'

# Remote server definitions
servers:
  test:
    password: 'password'
    table: 'test'

# Time formats
formats:
  duration: "'&f'H'&7h&f' m'&7m&f' s'&7s&r'"