# Configuration for ${project.name}
#
# Version: ${project.version}

plugin-prefix: "&aPlayTime &8>> "
debug-enabled: false

# Try to import time from statistics when a user with no record is created?
# There are no statistics on Bungee.
import-statistics: true

storage:
  # mysql/json
  type: json
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "password"
    database: "playtime"
    table: ""

# Time formats
formats:
  duration: "H 'h' m 'm' s 's'"