# Configuration for ${project.name}
#
# Version: ${project.version}

plugin-prefix: "&aPlayTime &8| "
debug-enabled: true

# Try to import time from statistics when a user with no record is created?
# There are no statistics on Bungee.
import-statistics: true

# Top cache update interval in seconds
top-cache-update-interval: 300

storage:

  # mysql/json
  # json is kinda.. not implemented yet.
  type: mysql

  # Settings for json.
  json:
    file-name: 'times.json'

  # General mysql settings.
  mysql:
    host: 'localhost'
    port: 3306
    username: 'root'
    password: 'password'
    database: 'playtime'

    # Reattempt loading with usernames?
    nick-reattempt: true

    # Table to use for local times.
    table: 'play-time'

use-remotes: true

# Settings for bungee network (or just multiple servers running with this plugin)
# All of them have to be running on MySQL.
servers:
  test:
    host: 'localhost'
    port: 3306
    username: 'root'
    password: 'password'
    database: 'playtime'
    table: 'test-remote'

# Time formats
formats:
  duration: "'&f'H'&7h&f' m'&7m&f' s'&7s&r'"