name: ${project.name}
version: ${project.version}
main: space.devport.wertik.playtime.spigot.PlayTimePlugin
authors: [Wertik1206]
softdepend: [PlaceholderAPI]
commands:
  playtime:
    description: Main plugin command.